//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookLoginTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostId { get; set; }
        public string UserId { get; set; }
        public string BloodType { get; set; }
        public string Age { get; set; }
        public string Location { get; set; }
        public string Illness { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
